### ISSUE TITLE
Aborted (core dumped) on unittest file

### ISSUE THREAD

**Issue by danakj** [hdoc/hdoc-github-action#1]
Here's the run: https://github.com/danakj/subspace/actions/runs/3342334037
Here's the commit: https://github.com/danakj/subspace/tree/4e5e6dd2bc0a0d1e12b80526c2a0fd18c279dfe1
Here's the yaml: https://github.com/danakj/subspace/blob/4e5e6dd2bc0a0d1e12b80526c2a0fd18c279dfe1/.github/workflows/ci.yml

Which contains:
```
      - name: Documentation
        if: startsWith(matrix.config.cxx, 'g++')
        uses: hdoc/hdoc-github-action@v2
        with:
          hdoc-api-key: ${{ secrets.HDOC_PROJECT_API_KEY }}
```

The "Ubuntu Latest GCC" builder runs hdoc in the "Documentation" step:

```
Run hdoc/hdoc-github-action@v2
/usr/bin/docker run --name d55819b[4](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:5)c7a87cd6a4c1cac96722997772b16_779bb7 --label 8d[5](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:6)581 --workdir /github/workspace --rm -e "INPUT_HDOC-API-KEY" -e "INPUT_COMPILE-COMMANDS-PATH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/subspace/subspace":"/github/workspace" 8d5581:9b4c7a87cd[6](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:7)a4c1cac96[7](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:8)22997772b16  "" "***"
grep: : No such file or directory
sed: : No such file or directory
[2022-10-2[8](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:9) 02:27:3[9](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:10).058] [info] hdoc version: 1.4.0-52b8ad2
[2022-[10](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:11)-28 02:27:39.058] [info] Timestamp: [20](https://github.com/danakj/subspace/actions/runs/3342334037/jobs/5534452493#step:8:21)22-10-28T02:27:39 UTC
[2022-10-28 02:27:39.058] [info] Root directory: /github/workspace
[2022-10-28 02:27:39.058] [info] Project name: subspace
[2022-10-28 02:27:39.058] [info] Project version: 0.0.1
[2022-10-28 02:27:39.058] [info] Indexing using all threads
[2022-10-28 02:27:39.738] [info] Starting indexing...
[2022-10-28 02:27:39.738] [info] Appending /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../include/c++/10.2.1 to list of include paths.
[2022-10-28 02:27:39.738] [info] Appending /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../include/c++/10.2.1/x86_64-alpine-linux-musl to list of include paths.
[2022-10-28 02:27:39.738] [info] Appending /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../include/c++/10.2.1/backward to list of include paths.
LLVM ERROR: Cannot chdir into "/home/runner/work/subspace/subspace/out"!
[2022-10-28 02:27:39.738] [info] Appending /usr/include to list of include paths.
[2022-10-28 02:27:39.739] [info] Appending /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/include to list of include paths.
[2022-10-28 02:27:39.739] [info] [1/42] processing /home/runner/work/subspace/subspace/option/option_unittest.cc
Aborted (core dumped)
```

I am going to omit my unit tests since I don't want to generate for them anyway, and see what happens, but I thought you'd like a crash report.

**Comment by danakj** [comment]
Putting `"_unittest.cc",` in `ignore.paths` doesn't stop it from crashing.

Run: https://github.com/danakj/subspace/actions/runs/3342368337

**Comment by hdoc** [comment]
> but I thought you'd like a crash report.

Absolutely, thank you for providing this detailed report. A quick glance shows that this is probably a result of GitHub Action's wonky checkout step, it tends to put the source of repositories into weird (undocumented) places that change between steps. We have some heuristics to deal with this but it's possible that something changed from underneath us. Let us investigate this further and we will get back to you.

Thanks.

**Comment by hdoc** [comment]
Turns out this was not a GitHub Actions problem, it was an issue with our GitHub Action choking when it wasn't provided the path to compile_commands.json. This argument is mandatory, and without it the action cannot perform the heuristics it needs to resolve paths in compile_commands.json. 

The following error message provided a clue:

```
grep: : No such file or directory
sed: : No such file or directory
```

Obviously, this isn't a great user experience on our part because there's no indication that the root cause of the failure is the missing argument. We will fix this in an upcoming release by adding an error when that path is not supplied and halting execution of the GitHub Action. We apologize for the inconvenience this may have caused.

Luckily, the fix wasn't too bad:

- Here's the patch where we added the missing argument: https://github.com/hdoc/subspace/commit/09a98084a2520f7a9be31a97ed8c3d825916f621
- Here's the successful workflow run post-patch: https://github.com/hdoc/subspace/actions/runs/3342732393/jobs/5535251293
- Lastly, here is the documentation for your project generated during the action above: https://docs.hdoc.io/g/subspace/docREADME.html

One quick note: hdoc does not currently have support for C++20 concepts, so the documentation for your project has some funky results, such as the documentation for this method being indexed three times. Support for concepts is a top priority for us and we'll be adding it soon, but until then some of these issues will be present in hdoc's output. We will use your project as a development tool to ensure we generate correct and helpful docs.

Thank you for reporting this bug!

**Comment by danakj** [comment]
> Turns out this was not a GitHub Actions problem, it was an issue with our GitHub Action choking when it wasn't provided the path to compile_commands.json. This argument is mandatory, and without it the action cannot perform the heuristics it needs to resolve paths in compile_commands.json.

Ah, thank you. I had removed it because the path is specified in my .hdoc.toml as well, and I saw that the .hdoc.toml was overriding the command line flag: it was trying to use out/ which is what I use locally, instead of build/ which is what the GitHub action was using.

> We will use your project as a development tool to ensure we generate correct and helpful docs.

Cool :) Thank you for working on this important software.

**Comment by hdoc** [comment]
>> Turns out this was not a GitHub Actions problem, it was an issue with our GitHub Action choking when it wasn't provided the path to compile_commands.json. This argument is mandatory, and without it the action cannot perform the heuristics it needs to resolve paths in compile_commands.json.
>
> Ah, thank you. I had removed it because the path is specified in my .hdoc.toml as well, and I saw that the .hdoc.toml was overriding the command line flag: it was trying to use out/ which is what I use locally, instead of build/ which is what the GitHub action was using.

Yes, unfortunately the path to compile_commands.json has to be specified twice, once in .hdoc.toml, and once in .ci.yml. This was done to avoid having to do the compile_commands.json path rewriting heuristics that I mentioned above within hdoc. This state of affairs is not ideal, but it made more sense to make them part of the GitHub Action instead of including platform-specific quirks in the C++ repo.

>> We will use your project as a development tool to ensure we generate correct and helpful docs.
>
> Cool :) Thank you for working on this important software.

Thank you for the kind comment and thank you for using hdoc. Likewise, I found your [PRINCIPLES.md](https://github.com/chromium/subspace/blob/main/PRINCIPLES.md) file to be an interesting read.
